# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ocimage < Formula
  desc "Build, tag, & push container images. No runtime dependencies."
  homepage "https://github.com/podplane/ocimage"
  version "1.0.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/podplane/ocimage/releases/download/v1.0.6/ocimage_1.0.6_darwin_amd64.tar.gz"
      sha256 "fe819a5d971912ba8e7410ebf7b32b93e58c0c2edb8ba138a9fbf50969624004"

      define_method(:install) do
        bin.install "ocimage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/podplane/ocimage/releases/download/v1.0.6/ocimage_1.0.6_darwin_arm64.tar.gz"
      sha256 "8398829ea515446ad43fe769064aed84868c3affbe9d41e8782b3e83a774688d"

      define_method(:install) do
        bin.install "ocimage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/podplane/ocimage/releases/download/v1.0.6/ocimage_1.0.6_linux_amd64.tar.gz"
      sha256 "b226b32d0fef82c053f910cd33fc010c239a567b168430bd4daab3672be33d80"
      define_method(:install) do
        bin.install "ocimage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/podplane/ocimage/releases/download/v1.0.6/ocimage_1.0.6_linux_arm64.tar.gz"
      sha256 "b787daedaefad4208f4bbfa614e505d364b1f75435bee4c9abecd4f744528d6e"
      define_method(:install) do
        bin.install "ocimage"
      end
    end
  end
end
