# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ocimage < Formula
  desc "Build, tag, & push container images. No runtime dependencies."
  homepage "https://github.com/podplane/ocimage"
  version "1.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/podplane/ocimage/releases/download/v1.0.2/ocimage_1.0.2_darwin_amd64.tar.gz"
      sha256 "ab9ea4299b3b1d7cc4348b73831a11150095b1548316cef4c7bc27b0e3ddf898"

      define_method(:install) do
        bin.install "ocimage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/podplane/ocimage/releases/download/v1.0.2/ocimage_1.0.2_darwin_arm64.tar.gz"
      sha256 "4901e450796da03eef04a826594b947a93972a93dc07889cebf7e585fa5990b8"

      define_method(:install) do
        bin.install "ocimage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/podplane/ocimage/releases/download/v1.0.2/ocimage_1.0.2_linux_amd64.tar.gz"
      sha256 "87fb87748910dcb4b1ffa47123a4b0ad603e1805ca78e6b35523185e40eba4b5"
      define_method(:install) do
        bin.install "ocimage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/podplane/ocimage/releases/download/v1.0.2/ocimage_1.0.2_linux_arm64.tar.gz"
      sha256 "dbf34e4e240bd6f532445a3b88a073fef7054866ec52bee55c43756ef3080d2d"
      define_method(:install) do
        bin.install "ocimage"
      end
    end
  end
end
