# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ocimage < Formula
  desc "Build, tag, & push container images. No runtime dependencies."
  homepage "https://github.com/podplane/ocimage"
  version "1.0.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/podplane/ocimage/releases/download/v1.0.8/ocimage_1.0.8_darwin_amd64.tar.gz"
      sha256 "acc2946f627582667c5f688b21ee686626d28c2394296800df04f4f1e9025098"

      define_method(:install) do
        bin.install "ocimage"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/podplane/ocimage/releases/download/v1.0.8/ocimage_1.0.8_darwin_arm64.tar.gz"
      sha256 "584ed18ac6a5ae2058b90c9f7acf32b9d6188d964400d15b1c14f8ca5eec21b5"

      define_method(:install) do
        bin.install "ocimage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/podplane/ocimage/releases/download/v1.0.8/ocimage_1.0.8_linux_amd64.tar.gz"
      sha256 "8cfe3c26e355a0b5d9bf91b7880272735c9f75e54954e61ff61152a956db42f8"
      define_method(:install) do
        bin.install "ocimage"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/podplane/ocimage/releases/download/v1.0.8/ocimage_1.0.8_linux_arm64.tar.gz"
      sha256 "e94627ca9af2f29c58096429548cf73293f251f5f304ca3b5ae5ec538ac34727"
      define_method(:install) do
        bin.install "ocimage"
      end
    end
  end
end
