# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Podplane < Formula
  desc "The official CLI for Podplane"
  homepage "https://podplane.dev"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/podplane/podplane/releases/download/v0.1.1/podplane_0.1.1_darwin_amd64.tar.gz"
      sha256 "d31585ada59fb1d7c2b053f0fb69afb90627535c943654e3a33dddacb63482ed"

      define_method(:install) do
        bin.install "podplane"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/podplane/podplane/releases/download/v0.1.1/podplane_0.1.1_darwin_arm64.tar.gz"
      sha256 "c1eabc08c86f502cc5c21809b6b2fb7e6f8079b62212bc9188a2d0320f7b1428"

      define_method(:install) do
        bin.install "podplane"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/podplane/podplane/releases/download/v0.1.1/podplane_0.1.1_linux_amd64.tar.gz"
      sha256 "0c543ca988856277e4d53b9350fbd64ac2e27f3655f70218aae55ae5336e00cc"
      define_method(:install) do
        bin.install "podplane"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/podplane/podplane/releases/download/v0.1.1/podplane_0.1.1_linux_arm64.tar.gz"
      sha256 "818568dcc55f4deafec213a3c8d99c39a87ea279bc4dfc7294546290d8f555d4"
      define_method(:install) do
        bin.install "podplane"
      end
    end
  end
end
