# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Podplane < Formula
  desc "The official CLI for Podplane"
  homepage "https://podplane.dev"
  version "0.8.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/podplane/podplane/releases/download/v0.8.0/podplane_0.8.0_darwin_amd64.tar.gz"
      sha256 "48894982800a9b6d2a8cae36d7c268f2e1aa08e72b3872990c7bd3f2b5c9f167"

      define_method(:install) do
        bin.install "podplane"
        bin.install_symlink "podplane" => "docker-credential-podplane"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/podplane/podplane/releases/download/v0.8.0/podplane_0.8.0_darwin_arm64.tar.gz"
      sha256 "7a72337ab27d997e50d8f726a51c9e7c4d0dab6e6347dbb5d484bc09baa266c4"

      define_method(:install) do
        bin.install "podplane"
        bin.install_symlink "podplane" => "docker-credential-podplane"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/podplane/podplane/releases/download/v0.8.0/podplane_0.8.0_linux_amd64.tar.gz"
      sha256 "a9fa1972c27f3bf207cbe9952237d0409dd2c786cc801103378756c0738e2347"
      define_method(:install) do
        bin.install "podplane"
        bin.install_symlink "podplane" => "docker-credential-podplane"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/podplane/podplane/releases/download/v0.8.0/podplane_0.8.0_linux_arm64.tar.gz"
      sha256 "888c05993d14ffed34bcfbbdab8a5f4cf0287ad8d7de9544b40f56d850a85052"
      define_method(:install) do
        bin.install "podplane"
        bin.install_symlink "podplane" => "docker-credential-podplane"
      end
    end
  end
end
