# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Podplane < Formula
  desc "The official CLI for Podplane"
  homepage "https://podplane.dev"
  version "0.5.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/podplane/podplane/releases/download/v0.5.3/podplane_0.5.3_darwin_amd64.tar.gz"
      sha256 "9f8ecb055e717074dad047a0b6e015e5be56c3399e5694f5b123366882ab9285"

      define_method(:install) do
        bin.install "podplane"
        bin.install_symlink "podplane" => "docker-credential-podplane"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/podplane/podplane/releases/download/v0.5.3/podplane_0.5.3_darwin_arm64.tar.gz"
      sha256 "a50107004e0b0eb85d544e1a3e3786dfdbb66706a8fe742de6fc1e1a5b43d648"

      define_method(:install) do
        bin.install "podplane"
        bin.install_symlink "podplane" => "docker-credential-podplane"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/podplane/podplane/releases/download/v0.5.3/podplane_0.5.3_linux_amd64.tar.gz"
      sha256 "5298fd8d99856b2bc685ac5a9b608c5ad35c8b02230ee223a9fb49aa3abdd9a5"
      define_method(:install) do
        bin.install "podplane"
        bin.install_symlink "podplane" => "docker-credential-podplane"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/podplane/podplane/releases/download/v0.5.3/podplane_0.5.3_linux_arm64.tar.gz"
      sha256 "7cf02442d05a10cfb26445f11a869d2836e0f92db88d10aefb1fe919a461d9ce"
      define_method(:install) do
        bin.install "podplane"
        bin.install_symlink "podplane" => "docker-credential-podplane"
      end
    end
  end
end
